language: android
android:
  components:
    # Update Android SDK Tools
    - tools
    - build-tools-24.0.2
    - android-24

    # Support library
    - extra-android-support
    - extra-android-m2repository

script:
   - ./gradlew build connectedCheck
